version: '3'

services:
  gateway-client-service:
    image: gateway-client-service-image:latest
    hostname: gateway
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - eureka_network
    ports:
      - '8080:8080'

networks:
  eureka_network:
    external: true