version: '3'

services:
  identity-user-service:
    image: identity-user-service-image:latest
    hostname: identity-service
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.generate-ddl=true
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - '8081:8081'
    networks:
      - gateway-server-service_eureka_network
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - gateway-server-service_eureka_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  gateway-server-service_eureka_network:
    external: true

volumes:
  postgres_data:
    driver: local