server:
  port: ${APPLICATION_PORT}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

spring:
  application:
    name: ${APPLICATION_PROJECT_NAME}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://gateway-server:8761/eureka/
