server:
  port: ${APPLICATION_PORT}
  servlet:
    context-path: /documentation

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

spring:
  application:
    name: ${APPLICATION_PROJECT_NAME}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: "*"

eureka:
  instance:
    hostname: gateway-client
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://gateway-server:8761/eureka/