service:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    root-user: ${MINIO_ROOT_USER}
    root-password: ${MINIO_ROOT_PASSWORD}
    bucket: ${MINIO_CLIENT_BUCKET_NAME}

server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: ${APPLICATION_PROJECT_NAME}

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: product-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://gateway-server:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs/index.html