server:
  port: ${APPLICATION_PORT}


spring:
  application:
    name: ${APPLICATION_PROJECT_NAME}

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect