service:
  access-token:
    lifetime: ${ACCESS_TOKEN_LIFETIME}
    private-key-path: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
  refresh-token:
    lifetime: ${REFRESH_TOKEN_LIFETIME}
    private-key-path: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
    public-key-path: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: ${APPLICATION_PROJECT_NAME}

  main:
    banner-mode: off

  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  jpa:
    open-in-view: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT_MS}
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS}
        max.block.ms: ${KAFKA_MAX_BLOCK_MS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

eureka:
  instance:
    hostname: identity-service
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://gateway-server:8761/eureka/